### ISSUE TITLE
Unknown build state

### ISSUE THREAD

**Issue by gbraad** [code-ready/tray-macos#23] opened 2020-02-18 05:27 UTC
The link in the README points to the wrong repo/build pipeline

**Comment by anjannath** [comment] 2020-02-18 05:53
Duplicate of #19, PR #22 handles this.

**Comment by anjannath** [comment] 2020-03-05 05:46
Fixed via https://github.com/code-ready/tray-macos/pull/22

**Closed by anjannath** 2020-03-05 05:46 UTC
